package com.boajp.vista;

import javax.swing.*;
import java.awt.*;

public class CartaMiembro {

    private JPanel panelPrincipal;
    private JLabel lbImage;
    private JLabel lbNombre;
    private JLabel lbFuncion;

    public CartaMiembro(ImageIcon imageIcon, String nombreCompleto, String funcion) {
        lbNombre.setText(nombreCompleto);
        lbFuncion.setText(funcion);
        lbImage.setIcon(imageIcon);
    }

    public JPanel getPanelPrincipal() {
        return panelPrincipal;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelPrincipal = new JPanel();
        panelPrincipal.setLayout(new GridBagLayout());
        lbImage = new JLabel();
        lbImage.setHorizontalAlignment(0);
        lbImage.setHorizontalTextPosition(0);
        lbImage.setText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 100.0;
        gbc.weighty = 90.0;
        panelPrincipal.add(lbImage, gbc);
        lbNombre = new JLabel();
        lbNombre.setText("Nombre Apellido");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 100.0;
        gbc.weighty = 5.0;
        panelPrincipal.add(lbNombre, gbc);
        lbFuncion = new JLabel();
        lbFuncion.setText("Funcion");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 100.0;
        gbc.weighty = 5.0;
        panelPrincipal.add(lbFuncion, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelPrincipal;
    }
/*
    public static void main(String... args) {
        Image image = new ImageIcon(CartaMiembro.class.getResource("/imagenes/logo.png")).getImage();
        JFrame frame = new JFrame();
        frame.add(new CartaMiembro(new ImageIcon(image), "Jorge Egea", "Presidente").getPanelPrincipal());
        frame.setSize(700, 500);
        frame.setVisible(true);
    }
*/
}
