DROP TABLE TEMPORADAS CASCADE CONSTRAINTS;
DROP TABLE SPLIT CASCADE CONSTRAINTS;
DROP TABLE JORNADAS CASCADE CONSTRAINTS;
DROP TABLE PARTIDOS CASCADE CONSTRAINTS;
DROP TABLE EQUIPOS CASCADE CONSTRAINTS;
DROP TABLE INFORMACION_EQUIPOS_PARTIDOS CASCADE CONSTRAINTS;
DROP TABLE CLASIFICACIONES CASCADE CONSTRAINTS;
DROP TABLE REGISTROS CASCADE CONSTRAINTS;
DROP TABLE JUGADORES CASCADE CONSTRAINTS;
DROP TABLE CONTRATO_EQUIPOS_JUGADORES CASCADE CONSTRAINTS;
DROP TABLE REGISTRO_MIEMBROS CASCADE CONSTRAINTS;
DROP TABLE DRAFTS ;
DROP TABLE PERMISOS CASCADE CONSTRAINTS;
DROP TABLE CUENTAS CASCADE CONSTRAINTS;

CREATE TABLE TEMPORADAS(
ID NUMBER(2) GENERATED ALWAYS AS IDENTITY
				INCREMENT BY 1
				START WITH 1
				NOCYCLE NOT NULL ENABLE,
ANO DATE,
FEC_INI_INS DATE,
FEC_FIN_INS DATE,
CONSTRAINT TEM_ID_PK PRIMARY KEY (ID)
);


CREATE TABLE SPLIT(
ID NUMBER(2) GENERATED ALWAYS AS IDENTITY
				INCREMENT BY 1
				START WITH 1,
NOMBRE VARCHAR2(20),
FECHA_INICIO DATE,
FECHA_FIN DATE,
ID_TEMPORADA NUMBER(2),
CONSTRAINT SPL_NOM_CK CHECK(NOMBRE IN('VERANO','INVIERNO')),
CONSTRAINT SPL_ID_TEM_FK FOREIGN KEY (ID_TEMPORADA) REFERENCES TEMPORADAS(ID),
CONSTRAINT SPL_ID_PK PRIMARY KEY (ID)
);


CREATE TABLE JORNADAS(
ID NUMBER(2) GENERATED ALWAYS AS IDENTITY
				INCREMENT BY 1
				START WITH 1,
NUM_JORNADA NUMBER(2),
FECHA DATE,
UBICACION VARCHAR2(50),
FASE VARCHAR2(20) default null,
ID_SPLIT NUMBER(2),
CONSTRAINT JOR_ID_PK PRIMARY KEY (ID),
CONSTRAINT JOR_ID_SPL_FK FOREIGN KEY (ID_SPLIT) REFERENCES SPLIT(ID)
);



CREATE TABLE PARTIDOS(
  ID NUMBER(2) GENERATED ALWAYS AS IDENTITY
      INCREMENT BY 1
      START WITH 1
      NOCYCLE NOT NULL ENABLE,
  HORA VARCHAR2(8),
  GANADOR VARCHAR2(50),
  ID_JORNADA NUMBER(2),
  CONSTRAINT PAR_ID_PK PRIMARY KEY (ID),
  CONSTRAINT PAR_ID_JOR_FK FOREIGN KEY (ID_JORNADA) REFERENCES JORNADAS(ID),
  CONSTRAINT PAR_CHK_HORA CHECK (HORA LIKE 'HH24:MI:SS')
);



CREATE TABLE EQUIPOS(
ID NUMBER(2) GENERATED ALWAYS AS IDENTITY
				INCREMENT BY 1
				START WITH 1,
NOMBRE VARCHAR2(50),
LOGO VARCHAR2(80),--¿?¿?¿?¿?
PRESUPUESTO NUMBER(10),
CONSTRAINT EQU_ID_PK PRIMARY KEY (ID)
);


CREATE TABLE INFORMACION_EQUIPOS_PARTIDOS(
ID_PARTIDO NUMBER(2),
ID_EQUIPO NUMBER(2),
NUM_GOLES NUMBER(2),

CONSTRAINT INF_ID_PK PRIMARY KEY (ID_PARTIDO, ID_EQUIPO),
CONSTRAINT INF_ID_PAR_FK FOREIGN KEY (ID_PARTIDO) REFERENCES PARTIDOS(ID),
CONSTRAINT INF_ID_EQU_FK FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID)

);


CREATE TABLE CLASIFICACIONES(
ID_SPLIT NUMBER(2),
ID_EQUIPO NUMBER (2),
POSICION NUMBER(2),

CONSTRAINT CLA_ID_PK PRIMARY KEY (ID_SPLIT, ID_EQUIPO),
CONSTRAINT CLA_ID_SPL_FK FOREIGN KEY (ID_SPLIT) REFERENCES SPLIT(ID),
CONSTRAINT CLA_ID_EQU_FK FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID)

);

CREATE TABLE REGISTROS(
ID NUMBER(2) GENERATED ALWAYS AS IDENTITY
				INCREMENT BY 1
				START WITH 1
				NOCYCLE NOT NULL ENABLE,
--NOMBRE VARCHAR2(50),
--APELLIDO VARCHAR2(50),
TELEFONO VARCHAR2(9),
EMAIL VARCHAR2(50),
DNI VARCHAR2(9)NOT NULL UNIQUE,

CONSTRAINT REG_IDR_PK PRIMARY KEY (ID)
);

--CAMBIAR ID JUGADORE
CREATE TABLE JUGADORES (
ID NUMBER(3) GENERATED ALWAYS AS IDENTITY
				INCREMENT BY 1
				START WITH 1
				NOCYCLE NOT NULL ENABLE,
ID_REGISTRO NUMBER(2),

CONSTRAINT JUG_ID_PK PRIMARY KEY(ID),
CONSTRAINT JUG_ID_REG_FK FOREIGN KEY (ID_REGISTRO) REFERENCES REGISTROS(ID)


);




CREATE TABLE CONTRATO_EQUIPOS_JUGADORES(
ID_EQUIPO NUMBER(2),
ID_JUGADOR NUMBER(3),
ID NUMBER(2) GENERATED ALWAYS AS IDENTITY
				INCREMENT BY 1
				START WITH 1
				NOCYCLE NOT NULL ENABLE,
SALARIO NUMBER(10),
CLAUSULA NUMBER(10),
FECHA_INICIO DATE,
FECHA_FIN DATE DEFAULT NULL,

CONSTRAINT CON_ID_PK PRIMARY KEY (ID),
CONSTRAINT CON_ID_JUG_FK FOREIGN KEY (ID_JUGADOR) REFERENCES JUGADORES(ID),
CONSTRAINT CON_ID_EQU_FK FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID)

);


CREATE TABLE REGISTRO_MIEMBROS (
ID_REGISTRO NUMBER(2),
NOMBRE VARCHAR2(50),
APELLIDO VARCHAR2(50),
ID_EQUIPO NUMBER(2),
FUNCION VARCHAR2(50),
FECHA_ENTRADA DATE,
FECHA_SALIDA DATE,

CONSTRAINT REG_MIE_ID_PK PRIMARY KEY (ID_REGISTRO),
CONSTRAINT REG_MIE_ID_REG_FK FOREIGN KEY (ID_REGISTRO) REFERENCES REGISTROS(ID),
CONSTRAINT REG_MIE_ID_EQU_FK FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID)
);

CREATE TABLE DRAFTS(
ID_TEMPORADA NUMBER(2),
ID_JUGADOR NUMBER(3),
POSICION NUMBER(2),

CONSTRAINT DRA_ID_PK PRIMARY KEY (ID_TEMPORADA, ID_JUGADOR),
CONSTRAINT DRA_ID_TEM_FK FOREIGN KEY (ID_TEMPORADA) REFERENCES TEMPORADAS(ID),
CONSTRAINT DRA_ID_JUG_FK FOREIGN KEY (ID_JUGADOR) REFERENCES JUGADORES(ID)
/*****************************ULTIMA CONSTRAINT DNI JUGADOR*********************************/
);


CREATE TABLE PERMISOS(
PERFIL VARCHAR2(50),
INSERTAR CHAR(1),
ELIMINAR CHAR(1),
ACTUALIZAR CHAR(1),
VER_VISTA CHAR(1),
VER_GLOBAL CHAR(1),
LANZAR_PRO CHAR(1),

CONSTRAINT PER_INS_CK CHECK(INSERTAR IN('S','N')),
CONSTRAINT PER_ELI_CK CHECK(ELIMINAR IN('S','N')),
CONSTRAINT PER_ACT_CK CHECK(ACTUALIZAR IN('S','N')),
CONSTRAINT PER_VVI_CK CHECK(VER_VISTA IN('S','N')),
CONSTRAINT PER_VGL_CK CHECK(VER_GLOBAL IN('S','N')),
CONSTRAINT PER_LAN_CK CHECK(LANZAR_PRO IN('S','N')),
CONSTRAINT PER_PERF_PK PRIMARY KEY (PERFIL)
);


CREATE TABLE CUENTAS (
ID NUMBER(2) GENERATED ALWAYS AS IDENTITY
				INCREMENT BY 1
				START WITH 1
				NOCYCLE NOT NULL ENABLE,
PERFIL VARCHAR2(50),
USUARIO VARCHAR2(50),
CONTRASENA VARCHAR2(20),
EMAIL VARCHAR2(50),

CONSTRAINT CUE_ID_PK PRIMARY KEY (ID),
CONSTRAINT CUE_PERF_PER_FK FOREIGN KEY (PERFIL) REFERENCES PERMISOS(PERFIL)

);