DROP PUBLIC SYNONYM TS;
DROP PUBLIC SYNONYM PS;
DROP PUBLIC SYNONYM JS;
DROP PUBLIC SYNONYM ES;

CREATE PUBLIC SYNONYM TS FOR TEMPORADAS;

CREATE PUBLIC SYNONYM JS FOR JORNADAS;

CREATE PUBLIC SYNONYM PS FOR PARTIDOS;

CREATE PUBLIC SYNONYM ES FOR EQUIPOS;
